name: rat
on:
  push:
    branches: [master, github_actions]
  pull_request:
    branches: [master, github_actions]
    types: [opened, synchronize]

jobs:
  license-check:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Check Rat
        run: mvn -B apache-rat:check -Prat
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
